### PR TITLE
Cmake fixes

### PR DESCRIPTION
**Pull request by johnmcfarlane**

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi @johnmcfarlane this is what you were telling me about, right, how the checks run on PR?

I'm not sure if I fully understand how to get that running, other than those `**` symbols in YAML. I think I need more details on how that works. Is this intended to be going to get into my repo too or remain on yours?

**Comment by johnmcfarlane** [comment]
@ckormanyos yes, that's right. I've just updated the "Branch protection rule" settings for the _master_ branch so now you can see that all the checks are required and all of them have passed.

I've made those settings in my fork and as per [!46](https://github.com/ckormanyos/wide-integer/issues/46) I'd encourage you to do the same so that I'm less likely to break your _master_ branch again!

The settings are under **Settings** -> **Branches** -> **Branch protection rules** -> **master** -> **edit** -> **Require status checks to pass before merging**. [Here's some documentation](https://docs.github.com/en/github/administering-a-repository/about-protected-branches#require-status-checks-before-merging). It's relatively safe for you to create an experimental PR with a failing test and play around until the PR is unmergeable. Then fix the test and watch the PR turn from red to green. (I find this very satisfying and reassuring.)

(There are other things you can do to protect _master_. E.g. you could require a code review. But as you're the only collaborator in your repo only you can merge anyway so that isn't necessary.)

As for this PR, it's a dupe of the one you already merged. I'm only leaving it open so you can see the checks and I'll be closing it later on.

**Comment by ckormanyos** [comment]
> encourage you to do the same...

OK. Right on! Thank you, John. I am getting on that.

I will tell you what I really want @johnmcfarlane ... On CI, to have reliable code coverage, with generation of HTML report(s) and perhaps some performance results. For the life of me, I find a complete lack of good code coverage tools. You can get pretty far with GCOV/LCOV on UNIX. But then You're pretty much out of luck on Win* with MSVC. Years Ago ancient MSVC had great coverage tools I think it was called `vsperf` or something like that, as did ancient Intel compiler(s) have awesome coverage instrumentation, but not so great on compilation time.

But I wonder if there is some kind of _gold standard_ out there for cover/perf handling modern C++20 template code with heavy use of `<type_traits>` and a decent level of compilation optimization? And I mean from this actual century that I'm not familiar with.

**Comment by johnmcfarlane** [comment]
I believe that GCOV/LCOV (or some similar LLVM variant) is the current go-to for FOSS solutions. (There are also alternatives to LCOV for the report generation.)

I used it [here](https://github.com/johnmcfarlane/wss/blob/master/scripts/coverage.sh) and on other projects. It's fiddly and flawed but not terrible.

You need to bear in mind that coverage is always going to be an inexact science because the language is allowed to generate any code it likes -- provided the observable behavior matches (the 'as if' rule). So trusting the numbers you get out always requires a leap of faith, namely from the actual machine to the abstract machine.

As such, I do not worry too much about the MSVC coverage testing: if my tests are all run on both systems and I don't have any major differences in the implementation (of the `#ifdef(_MSC_VER)` variety), then I feel confident that coverage numbers for one system track numbers for both to a reasonable degree.

**Comment by ckormanyos** [comment]
I appreciate that coverage shell scripting. Looks clean.

Back to the original topic, I will follow your progress and attempt to use such things. I think these CMake improvements should/could also work well for adaptions of the wide-integer project itself.

Thanks for moving forward on this.

**Comment by ckormanyos** [comment]
@johnmcfarlane this was actually a cool experience because I had some recent changes and the _warning_ _as_ _error_ in `CMake` caught some MSVC level 4 warnings that I otherwise would not have noticed. I ended up correcting the errors and also setting my MSVC projects to level `/W4`, without `-werror`. But it was a cool CI catch. Thanks for setting up the CMake scripts.

**Pull request closed without merging**
